version: 2
jobs:
  build:
    machine:
     docker_layer_caching: true
    steps:
     - checkout
     - run:
        command: |
          docker login -u=$HEROKU_LOGIN -p=$HEROKU_API_KEY registry.heroku.com
          docker build --rm=false -t registry.heroku.com/$HEROKU_APP_NAME/web .
          docker push registry.heroku.com/$HEROKU_APP_NAME/web:latest
          imageId=$(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}})
          payload='{"updates":[{"type":"web","docker_image":"'"$imageId"'"}]}'
          curl -n -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
          -d "$payload" \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"

workflows:
  version: 2
  build_app:
    jobs:
      - build




